lines = [
    "# Render.com multi-service deployment",
    "# Deploy: render.com > New > Blueprint > Connect repo",
    "",
    "services:",
    "",
    "  # ── FastAPI Backend ────────────────────────────────────",
    "  - type: web",
    "    name: lumora-ai-backend",
    "    runtime: python",
    "    rootDir: backend",
    "    buildCommand: pip install -r requirements.txt",
    "    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT",
    "    healthCheckPath: /health/",
    "    autoDeploy: true",
    "    envVars:",
    "      - key: ENVIRONMENT",
    "        value: production",
    "      - key: DEBUG",
    "        value: false",
    "      - key: APP_NAME",
    "        value: Lumora AI",
    "      - key: PYTHON_VERSION",
    "        value: 3.12.0",
    "      # Set these in Render dashboard (secret values)",
    "      - key: SECRET_KEY",
    "        generateValue: true",
    "      - key: JWT_SECRET_KEY",
    "        generateValue: true",
    "      - key: GEMINI_API_KEY",
    "        sync: false",
    "      - key: OPENAI_API_KEY",
    "        sync: false",
    "      - key: LLM_PROVIDER",
    "        value: gemini",
    "      - key: GEMINI_MODEL",
    "        value: gemini-2.0-flash",
    "      - key: VECTOR_STORE_PATH",
    "        value: /tmp/vector_store",
    "      - key: LANGCHAIN_TRACING_V2",
    "        value: false",
    "      # These are auto-set by Render from the database/redis services",
    "      - key: DATABASE_URL",
    "        fromDatabase:",
    "          name: lumora-ai-db",
    "          property: connectionString",
    "      - key: REDIS_URL",
    "        fromService:",
    "          name: lumora-ai-redis",
    "          type: redis",
    "          property: connectionString",
    "      # Set CORS_ORIGINS after frontend deploys",
    "      - key: CORS_ORIGINS",
    "        sync: false",
    "",
    "  # ── Next.js Frontend (Static) ─────────────────────────",
    "  - type: static",
    "    name: lumora-ai-frontend",
    "    rootDir: frontend",
    "    buildCommand: npm ci && npm run build",
    "    staticPublishPath: out",
    "    autoDeploy: true",
    "    routes:",
    "      - type: rewrite",
    "        source: /*",
    "        destination: /index.html",
    "    headers:",
    "      - path: /*",
    "        name: X-Frame-Options",
    "        value: DENY",
    "      - path: /*",
    "        name: X-Content-Type-Options",
    "        value: nosniff",
    "      - path: /static/*",
    "        name: Cache-Control",
    "        value: public, max-age=31536000, immutable",
    "    envVars:",
    "      - key: NEXT_PUBLIC_API_URL",
    "        sync: false",
    "",
    "  # ── Redis ───────────────────────────────────────────────",
    "  - type: redis",
    "    name: lumora-ai-redis",
    "    plan: free",
    "    maxmemoryPolicy: allkeys-lru",
    "",
    "databases:",
    "  # ── PostgreSQL ──────────────────────────────────────────",
    "  - name: lumora-ai-db",
    "    databaseName: lumora_ai",
    "    user: lumora_user",
    "    plan: free",
]
with open("render.yaml", "w", encoding="utf-8", newline="\n") as f:
    f.write("\n".join(lines) + "\n")
print("render.yaml written!")

